version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
        dependency_type: "development"
        update_type: "all"
      - match:
        dependency_type: "production"
        update_type: "semver:minor"
    version_requirement_updates: "auto"
