name: Docs
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 'stable'
          target: 'thumbv7em-none-eabihf'
          override: true
      - name: Cargo Doc
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --verbose --no-deps --document-private-items --features=xmc41xx
      # - name: Cargo Install
      #   uses: actions-rs/cargo@v1.0.3
      #   with:
      #     command: install
      #     args: cargo-ghp-upload
      # - name: GHP Upload
      #   uses: actions-rs/cargo@v1.0.3
      #   with:
      #     command: ghp-upload
      #   env:
      #     'GH_TOKEN': ${{ secrets.GH_TOKEN }}
